version: '3.9'
services:
  app:
    container_name: ${DOCKER_CONTAINER_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${APP_HOST_PORT}:${DOCKER_CONTAINER_PORT}"
    volumes:
      - .:/app
      - ./data:/app/data
